# -*- coding: utf-8 -*-
"""env.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMOKTnyVCk-5zVMtXVE3G5vOYeWQNQvW
"""

!apt install python3.10-venv

import os

   # Set the name of your virtual environment
   venv_name = 'myenv'

   # Create the virtual environment
   !python -m venv /content/$venv_name

# Activate the virtual environment
   !source /content/$venv_name/bin/activate

# Install Streamlit in the virtual environment
   !pip install streamlit

# Run your Streamlit app
   !streamlit run capstone.py